### ISSUE TITLE
Jeopardy first round issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#1]
- [ ] All functions with await need async (e.g. https://github.com/RodriguezRamiro/Usf/blob/3b16a438b18c405ad48d0e8ed436f8bece0fd2b1/19JeopardyAssessment2/jeopardy/jeopardy.js#L30)
- [ ] NUM_CATEGORIES is uninitialized.
- [ ] Jeopardy answer & question squares not showing up. (screenshot: ![image](https://github.com/user-attachments/assets/70b21945-7bc1-433d-8d53-898495066395) )

**Comment by RodriguezRamiro** [comment]
revised game logic fixed issues:
Jeopardy answer & question squares not showing up.
NUM_CATEGORIES is uninitialized.
All functions with await need async
https://github.com/RodriguezRamiro/Usf/commit/c297cd52d99340ac13719bb2134d2af6ca5e3608


<img width="949" alt="Screenshot 2024-10-13 at 5 59 06 PM" src="https://github.com/user-attachments/assets/0a0816dd-d600-4038-897e-db00fedf6f35">
