### ISSUE TITLE
39.1 Jobly - First round of issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#10]
- [x] user.js: There was a static function outside of a class.  Static functions should only exist within classes.
- [x] sql.js: There was some pseudo code that was left in.  This breaks trying to start the node server (`npm run start`)
- [x] users.js: There is a line of code that is referencing the solution.  `const { ensureAdmin, ensureCorrectUserOrAdmin } = require("../../express-jobly-solution/middleware/auth");`

**Comment by RodriguezRamiro** [comment]
revised and restructured code to fix issues and mistakes:
 user.js: There was a static function outside of a class. 
 sql.js: There was some pseudo-code that was left in. 
 users.js: There is a line of code that is referencing the solution. (rookie mistake😂)

https://github.com/RodriguezRamiro/Usf/commit/8d77d00b4cbf738ae575f0306db6fb6634c70d53
