### ISSUE TITLE
8.4.6 TODO app Second round

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#14]
Here are the directions:
https://lessons.springboard.com/JS-Todos-Exercise-d2e067f2a18545b891bf0e237fc37663 

Per the directions, the only thing you are missing is "**Mark a todo as completed (cross out the text of the todo)**"

Once this is completed, this project will be a pass :).

**Comment by RodriguezRamiro** [comment]
revised code to fix missing functionality:
"Mark a todo as completed (cross out the text of the todo)"

https://github.com/RodriguezRamiro/Usf/commit/6b609ac26ab3b7a69bc7e99c57cacc63c343040b

**Comment by CodyTVWeber** [comment]
Looks like you put in some code for the completion button.  But it is not seen in the app:
![image](https://github.com/user-attachments/assets/0e5971ea-3d67-44b2-874f-9d56e23a8d75)

**Comment by CodyTVWeber** [comment]
Alrighty, looks good!
