### ISSUE TITLE
Jeopardy second round

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#16]
Looks like everything is mostly working except the first and second clicks seem to **not** be updating the text properly.  When clicked, the the ? goes directly to answer.

This is the desired behavior:
1. The 1st click should go to the question first
2. then the second click should go to the answer.

It might have something to do with the handleClick() function.
![image](https://github.com/user-attachments/assets/e61e64b5-530b-4aaf-b11e-4c7866e16871)

**Comment by RodriguezRamiro** [comment]
reworked handle click function to achieve desired behavior:

The 1st click should go to the question first
then the second click should go to the answer.

after some research added evt.stopPropagation() to prevent the event from bubbling up the DOM tree. tested and seems to be working as it should.

<img width="460" alt="Screenshot 2024-10-17 at 5 25 13 PM" src="https://github.com/user-attachments/assets/5ef33e2f-a701-42a0-98ef-f43ea385ea0a">


https://github.com/RodriguezRamiro/Usf/commit/3bb554579915ffc58ad2f05b791c539d7a070bb0

**Comment by CodyTVWeber** [comment]
Looks good!
