### ISSUE TITLE
30.1 Twitter Clone - Issues round two

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#18]
- [ ] App context needed for DB connection
- [ ] home.html jinja ifs and fors are malformed.  Please correct this for all the html files.
- [ ] There are likely further issues after this, but I was unable to see them because the html files were not working.

**Comment by RodriguezRamiro** [comment]
refactored code to fix issues and functionality:    
 App context needed for DB connection
 home.html jinja ifs and fors are malformed.

managed to get the app running and made sure everything was functional. 

<img width="1198" alt="Screenshot 2024-10-19 at 2 36 36 PM" src="https://github.com/user-attachments/assets/85f38302-b401-4a78-aaa0-cfe26ef3595c">


https://github.com/RodriguezRamiro/Usf/commit/bdfe73e50bef9e0043b118bf20061417ae6d5584

**Comment by CodyTVWeber** [comment]
Passed!
