### ISSUE TITLE
8.4.6 TODO app first round

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#2]
**In reference to running the `jsTodoList.html` file:**
Looks like the function "addTask()" is malformed.  Because the outside the function, the app is trying to reference function-scoped variable called "newTask" outside of the function.  So whenever attempting to add a task with value "Take out trash", the console logs this error:
```
Uncaught ReferenceError: newTask is not defined
    at jsTodoList.js:17:26
```

With the help of AI, this app should be pretty quick to fix.  It looks like the main logic is there.

**Comment by RodriguezRamiro** [comment]
revised and fixed todo app: https://github.com/RodriguezRamiro/Usf/commit/774ff61db2fcc58e7d236b4c44508dc2ceecee8e
