### ISSUE TITLE
8.5 Memorygame - First round

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#3]
Overall the app mostly works for the actual game portion.  But has many bugs.  

Here are a few:
- [ ] Score and timer do not update.  They are always 0.
- [ ] Start game and Reset game buttons do not seem to do anything.
- [ ] Able to click a new tile + a previously matched tile which counts as a match. (Hopefully that makes sense.  Pretty odd bug.)
![image](https://github.com/user-attachments/assets/baf79cd3-c2bb-4c57-8242-6b6ce338d8f7)

**Comment by RodriguezRamiro** [comment]
revised and refactored code to fix issues:
here's the link:
https://github.com/RodriguezRamiro/Usf/commit/74b44b2a82f6b11cd6fc1374ec33ea4b8efd54a7

ill work on the rest.

**Comment by CodyTVWeber** [comment]
Yep looks like these issues are fixed.  Passed.
