### ISSUE TITLE
9.1 Meme Generator - First round of issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#4]
- [ ] Random text at the top
- [ ] Broken meme image below
![image](https://github.com/user-attachments/assets/6e94253e-689a-424a-a3cf-6992d5180873)

- [ ] Attempting to create a meme causes screen to flash, but then no meme appears.
![image](https://github.com/user-attachments/assets/6df82013-de2d-4f74-971c-34308fa9aed1)

**Comment by RodriguezRamiro** [comment]
revised code fixed issues and logic: https://github.com/RodriguezRamiro/Usf/commit/66932f2de418b1f4ec7edd2210db974c44c25618
