### ISSUE TITLE
16.1 Car OO Challenge - First round of issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#5]
These issues arose whenever I attempted to load this JS into a web browser to interact with the JS:
- [ ] Variable is initialized multiple times. (https://github.com/RodriguezRamiro/Usf/blob/3b16a438b18c405ad48d0e8ed436f8bece0fd2b1/16.1CarOOChallenge.js#L10)
- [ ] `new Vehicle(...)` is used before class Vehicle has been defined. (https://github.com/RodriguezRamiro/Usf/blob/3b16a438b18c405ad48d0e8ed436f8bece0fd2b1/16.1CarOOChallenge.js#L10)

**Comment by RodriguezRamiro** [comment]
revised car 16.1CarChallenge and refactored logic. fixed issues: 
Variable is initialized multiple times. 
new Vehicle(...) is used before class Vehicle has been defined.
https://github.com/RodriguezRamiro/Usf/commit/d9308688f8349c82d1bf4d38c57c150ec0049ff8

**Comment by CodyTVWeber** [comment]
Good job!  Passed!
