### ISSUE TITLE
16.2 Connect Four OO - First round of issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#6]
- [ ] Malformed line of code. (https://github.com/RodriguezRamiro/Usf/blob/3b16a438b18c405ad48d0e8ed436f8bece0fd2b1/16.2ConnectFourOO.js#L154)
- [ ] Malformed constructor. (https://github.com/RodriguezRamiro/Usf/blob/3b16a438b18c405ad48d0e8ed436f8bece0fd2b1/16.2ConnectFourOO.js#L149)

**Comment by RodriguezRamiro** [comment]
revised and refactored game logic to fix issues:
Malformed line of code.
Malformed constructor.
https://github.com/RodriguezRamiro/Usf/commit/c5248e083cbdb86b47ac4eefe4c1444c798e4fe0

**Comment by CodyTVWeber** [comment]
Good job!  Passed!  There was still an issue with alignment.  But not a big deal to me, as long as things still worked generally.
