### ISSUE TITLE
15.1	Predictive Text Project - First round of issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#7]
Looks like this whole app was essentially not done.  TODOs everywhere.

But the first main callout is that this function is very broken:
```js
function search(str) {
	let search = [];
	const results = fruit.filter(fruit => fruit.toLowerCase().includes(searchTerm));
		const searchTerm = document.getElementById('fruit').value;
	// TODO
	return results;
}
```

**Comment by RodriguezRamiro** [comment]
revised and refactored app logic. removed todos and completed functionality

https://github.com/RodriguezRamiro/Usf/commit/24ec0d85ae231e958a6333014ee435ad7e998e40

**Comment by CodyTVWeber** [comment]
The only issue I see is that the background gradient is not correct, but it is close enough in my opinion.  Passed :)
