### ISSUE TITLE
29 Databases - First round of issues

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#8]
Can't run as is:
- [ ] forms.py has the edit form incorrectly named which is breaking how app.py is importing it.
- [ ] app.py has quite a few compile errors.  All of them seem to relate around attempting to use the variable `user`, which was never declared.

**Comment by RodriguezRamiro** [comment]
revised app logic and restructured code to fix issues. However, I can't seem to run it on my machine for some reason flask keeps giving me an error I have reinstalled it several times and it says the app can not be found. please let me know if it works I attached a screenshot of the error seems I don't know how to figure it out. 

![Screenshot 2024-10-14 at 2 17 32 PM](https://github.com/user-attachments/assets/1f5b7b6d-70c8-412f-abe6-924cd6f63e3b)

https://github.com/RodriguezRamiro/Usf/commit/9aebc8a856dd62ae81d5ae330cb2e7ba9ba985e0

**Comment by CodyTVWeber** [comment]
We met yesterday to help him with running flask properly.
