### ISSUE TITLE
30.1 Twitter Clone - Please create project folder

### ISSUE THREAD

**Issue by CodyTVWeber** [RodriguezRamiro/Usf#9]
It looks like there are several python projects that we mixed together.  Please put the appropriate projects into their own folders so that way the files are not being changed from project to project.

If help is needed for this, please let me know, I should be able to help with this.

**Comment by RodriguezRamiro** [comment]
revised files and code and added them into one single directory hope that works thanks.

https://github.com/RodriguezRamiro/Usf/commit/9360878acbf2f4d7c1034a26d1090c31ae596756
